project:
  type: manuscript

format:
  html:
    theme: [default, paper.scss]
    toc: true
    toc-depth: 2
    number-sections: true
    code-fold: true
    citations-hover: true
    footnotes-hover: true
    comments:
      hypothesis:
        theme: clean
        openSidebar: false
        showHighlights: whenSidebarOpen

bibliography: references.bib

filters:
  - ../../_extensions/mloubout/critic-markup/critic-markup.lua

critic-mode: markup

execute:
  echo: false
  warning: false
  message: false
